const routes = {
  AUTH: {
    SIGN_IN: "/auth/sign-in",
    SIGN_UP: "/auth/sign-up",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/reset-password",
    VERIFICATION: "/verification",
    VERIFICATION_SUCCESS: "/verification/success",
    VERIFICATION_FAILED: "/verification/failed",
    SIGN_IN_SUCCESS: "/auth/success",
  },
  CUSTOMER: {
    HOME: "/",
    BOOK_DETAIL: "/book/:bookId",
    CART: "/checkout/cart",
    CHECKOUT: "/checkout/payment",
    PURCHASE: "/customer/purchase",
    ORDER_DETAIL: "/customer/purchase/:orderId",
    ACCOUNT_PROFILE: "/customer/account/profile",
    ACCOUNT_ADDRESS: "/customer/account/address",
    CHANGE_PASSWORD: "/customer/account/password",
  },
  ADMIN: {
    DASHBOAD: "/dashboad",
    ORDER: "/portal/order",
    ORDER_DETAIL: "/portal/order/:orderId",
    PRODUCT: "/portal/book",
    ADD_PRODUCT: "/portal/book/new",
    PRODUCT_DETAIL: "/portal/book/:bookId",
    CATEGORY: "/portal/category",
    REVIEW: "/portal/rating",
    REPORT: "/datacenter/overview",
    BOOK_REPORT: "/datacenter/book/overview",
    INCOME_REPORT: "/datacenter/income/overview",
    ACCOUNT_PROFILE: "/admin/account/profile",
    CHANGE_PASSWORD: "/admin/account/password",
    CUSTOMER: "/admin/customer",
  },
};
export default routes;
